### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [czechboy0/Socks#19]
Hi,
It's will be great to add [Carthage](https://github.com/Carthage/Carthage) support

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by czechboy0** [comment]
Hi @TofPlay,

do you have a project where you'd use that? Currently Socks is using the latest Swift 3.0 snapshot and it's going to for the foreseeable future. I was considering adding both CocoaPods & Carthage support eventually, once Swift 3 is out and Socks' API stabilizes. 

I could look at it later, but if you need it sooner, feel free to send a PR. I wouldn't see a reason to not merge it. :blush:

**Comment by czechboy0** [comment]
@TofPlay I'll close this for now, since there isn't a *next step* from our side. As I mentioned above, feel free to send a PR with Carthage support, but we won't spend time on supporting CocoaPods/Carthage just yet as this is a server-facing package rather than iOS etc.

**Comment by JetForMe** [comment]
> @TofPlay I'll close this for now, since there isn't a _next step_ from our side. As I mentioned above, feel free to send a PR with Carthage support, but we won't spend time on supporting CocoaPods/Carthage just yet as this is a server-facing package rather than iOS etc.

Just FYI, if one needs to embed a web server in a macOS or iOS app (I have had to more than once), Carthage support would be ideal.

**Comment by 0xTim** [comment]
Correct me if I'm wrong but I don't think Carthage support is something that will ever happen, due to the way SPM and Carthage just don't play nice. Carthage requires a projects scheme to be shared. SPM doesn't have a project file so making them work together will likely cause some issues.

Don't get me wrong, I think full Vapor support on iOS is something that should be worked on, but it's most likely to come via SPM (especially now that NIO supports iOS) or failing that Cocoapods (which brings its own problems).
